site_name: Research group name

theme:
  name: null
  custom_dir: sparrow-v1.6.2
  colorscheme: github
  highlightjs: true
  # custom theme configs
  navigation_depth: 2
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s


nav:
  - What selfies mean for avatars in VR and the way we perceive ourselves: text1.md

markdown_extensions:
  - admonition
