site_name: Research group name
dev_addr: 127.0.0.1:8001

theme:
  name: null
  custom_dir: sparrow-v1.6.2
  colorscheme: github
  highlightjs: true
  # custom theme configs
  navigation_depth: 2
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s


nav:
  - Amazon is eating the software (which is eating the world around us): text1.md
  - Text2: text2.md

markdown_extensions:
  - admonition
