site_name: Research group name
dev_addr: 127.0.0.1:8001

theme:
  name: null
  custom_dir: sparrow-v1.6.2
  colorscheme: github
  highlightjs: true
  # custom theme configs
  navigation_depth: 2
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

nav:
  - What scientists do and don’t know about the Oxford–AstraZeneca COVID vaccine: text1.md
  - The fight against fake-paper factories that churn out sham science: text2.md
  - DNA-driven condensation assembles the meiotic DNA break machinery: text3.md
  - Form a climate club United States, European Union and China: text4.md
  - Effects of rising CO2 levels on carbon sequestration are coordinated above and below ground: text5.md
  - Atomic clocks compared with astounding accuracy: text6.md
  

markdown_extensions:
  - admonition
